---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ro
  namespace: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres16
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-rw
  namespace: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres16
    role: primary
  sessionAffinity: None
