---
collections:
  - name: community.general
    version: 7.2.0
  - name: community.sops
    version: 1.6.4
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.10.3
  - name: kubernetes.core
    version: 2.4.0
  - name: devsec.hardening
    version: 9.0.0

roles:
  # Galaxy v3.3.0 not working: https://github.com/PyratLabs/ansible-role-k3s/issues/196
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.2
  - name: andrewrothstein.starship
    src: https://github.com/andrewrothstein/ansible-starship.git
    version: v1.1.6
  - name: hifis.unattended_upgrades
    src: https://github.com/hifis-net/ansible-role-unattended-upgrades.git
    version: v3.2.1
