---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tontontresors.com"
  namespace: default
spec:
  secretName: "tontontresors.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "tontontresors.com"
