---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.yaml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
