---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "s3.${PUBLIC_DOMAIN}"
  namespace: storage
spec:
  secretName: "s3.${PUBLIC_DOMAIN}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "s3.${PUBLIC_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "minio.${PUBLIC_DOMAIN}"
  namespace: storage
spec:
  secretName: "minio.${PUBLIC_DOMAIN}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "minio.${PUBLIC_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "cdn.tontontresors.com"
  namespace: storage
spec:
  secretName: "cdn.tontontresors.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "cdn.tontontresors.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "cdn.scarfsage.com"
  namespace: storage
spec:
  secretName: "cdn.scarfsage.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "cdn.scarfsage.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "cdn.dotb.io"
  namespace: storage
spec:
  secretName: "cdn.dotb.io"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "cdn.dotb.io"
