---
# https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: minio
      version: 14.8.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  values:
    image:
      registry: docker.io
      repository: bitnami/minio
      tag: 2024.10.13-debian-12-r0
    auth:
      rootUser: admin
      existingSecret: minio
    persistence:
      enabled: true
      existingClaim: minio
    metrics:
      serviceMonitor:
        enabled: true
        namespace: monitoring
    extraEnvVars:
      - name: TZ
        value: "${TIMEZONE}"
      - name: MINIO_PROMETHEUS_URL
        value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
      - name: MINIO_PROMETHEUS_JOB_ID
        value: minio
      # - name: MINIO_BROWSER_REDIRECT_URL
      #   value: "https://s3.${PUBLIC_DOMAIN}"
      # - name: MINIO_SERVER_URL
      #   value: "https://s3.${PUBLIC_DOMAIN}"
      # - name: MINIO_API_CORS_ALLOW_ORIGIN
      #   value: "https://s3.${PUBLIC_DOMAIN}"
    # Minio dashboard
    ingress:
      enabled: true
      ingressClassName: "traefik"
      hostname: &dashboard_host "minio.${PUBLIC_DOMAIN}"
      extraTls:
        - hosts:
            - *dashboard_host
          secretName: *dashboard_host
    apiIngress:
      enabled: true
      ingressClassName: "traefik"
      hostname: &api_host "s3.${PUBLIC_DOMAIN}"
      extraTls:
        - hosts:
            - *api_host
          secretName: *api_host
    resources:
      requests:
        memory: "3584Mi"
        cpu: "100m"
      limits:
        memory: "3584Mi"
