apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage
type: Opaque
stringData:
    root-user: ENC[AES256_GCM,data:RYizAE0=,iv:4DUBiCPZ3/RvVlgs7mPK4I9QucXLM5i5yVzg6p5UvXE=,tag:EznzYmqQJG+8VtoNeS098g==,type:str]
    root-password: ENC[AES256_GCM,data:menT4bqCH+EZkTOS0VO/52AL75gWrAGGlf8IfwTyqpU=,iv:tsHbLAM/0ZHlMBA5U54UEotcjpF+W2XCONh9r+C1Q3k=,tag:uAiadm6vxx8l6V6gM0s5FQ==,type:str]
    access_key: ENC[AES256_GCM,data:U7hdyKQF9Jn0ASvEQ6Wb74OlP7w=,iv:Nut6Uk9Xn9AOv/DIwspg203uiJg7i6mR8BnrXeKUWTo=,tag:2lc33hNr3B8edL4kdTYaEg==,type:str]
    secret_key: ENC[AES256_GCM,data:5dQ0GwtLVpodKYHSguSsqQaBXsak/zvweW9TGpTAObNvdyyZoByKCQ==,iv:/wtn144L/R0BPxJAv8WEaeYANN1hTTzsbyPum57sH4c=,tag:2WK9LINhGrHcWGzuu4R5Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSlJlMkpRMnM0UFpZNEVH
            L1R3QlRpc3g3czMzclI4QjBhVjFwOCtuTTNvCjE1VVNUL1RuM01mVjhzQ0lORTk2
            aVRONHhVbHB5R2x6T1BRZEdHc1ZKVHcKLS0tIFFHR3NLczY0bnJ2QnYvaEwxM0cy
            V09MOHFlSTdHa25iT3ZYVWluOElmVDAKj+b838jtFNfai72BJ7jrWI6jicjtvM7V
            22LehY9Fmyeu1iR13a8rLDxvshwWMYda4kDdI7EgpHANz7kjBNFkhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T16:47:35Z"
    mac: ENC[AES256_GCM,data:N8slPoHsnwK7ePzPIN5JIbCuqJoqH099QPHJgVcnazQ5/liPfGLjcBPIx+hGb784kVH8V2iCZlSqo7RBe2Na9RWV+up1zOVVomrQYFXiGVJ/Eu9vUUi60y35C+uhqrtijJXQEpcBMGyvAhKjNSPJVd/zTgCi867w4zpSBmvJk0g=,iv:cpmGHOv4CxdiFIaE+voSWSopZopA3Ty7tdTz2AgjFBQ=,tag:qLeJd2KtnOzhYCEqI0tkRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
