---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vintagesta
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/vintagesta/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: thousand-sunny
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
