apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
type: Opaque
stringData:
    access_key: ENC[AES256_GCM,data:eZW4U9CvaQYdV81PTxobHiPq8vg=,iv:O5KaXUw/+3AcJzQikZeDnikvoNTBRhp/ELvWLVV/r/8=,tag:/UEa6Gdt+1J0PFuiVr5bbA==,type:str]
    secret_key: ENC[AES256_GCM,data:6W6v2j17hn4lAe93+41rVJPMqxYzeE4g6XPqh26PEvd6Rr9ucw5psg==,iv:V1yXuyOV7A0tHmWCsse/7KrYRd7ugqX2V+TTC+hZRu8=,tag:BI9oHtgxXIglUsvQ60cpgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTnVIdHc1bnhrWmR5SUd4
            UWFPa1prRkhIR0RHTVRqNXhrZEFQbzJ4cGpZCkd6d1hQbXRwQmF5Qm5MQjF1WU5Y
            bWZ6OHM4bkc2ZjFOWnJOWjhBV1NtdXcKLS0tIGhwd2lvZDdiQ2RtcDg2dGZFa1hi
            d2wzVEsyN1k2ak8vTG9LUGhtSXZHRWcKJp3V0aZSkKwmWKQ/DO8nQGrS7HZ4ck5n
            8Vg6DBjg9skZS9wgShk6qbiFLC46LH0QNyVVhxLrauIHIgeaYeWpWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-01T17:56:38Z"
    mac: ENC[AES256_GCM,data:ISM1Hwcca9ibqYZmFqws7JELUsXcJsjxjh5+ie8B0pd0wqJlzAlhdb8rA8h7GvekmY4qu6bp1VgLXEgwLT341fIHH/E0oYl2gszLlikEZ1KCFJHohTcbjlQEYsHPhQlyKxu4Jve1lyEf7ZoVzYbpHxg9RGwNODB0jnPumv/NkuE=,iv:KrU+a03TCJh+c84ObtbdCn4q8gxw0ODtPT9JCD7S5co=,tag:/KYa2ZTKP8stNUIkyVKXcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
