---
- hosts:
    - kubernetes
  become: true
  # roles:
    # TODO maybe disable swap
    # https://github.com/brettinternet/homelab/blob/main/provision/ansible/roles/os/tasks/debian-swap.yaml
    # - os
    # - role: upgrade
    #   vars:
    #     allow_reboot: false
  tasks:
    - name: Install packages
      ansible.builtin.package:
        state: latest
        name:
          - base
          - git
          - vim
          - tmux
          - curl
          - zsh
          - htop
          - ncdu
