---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-ingress-nginx
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: apps-ingress-nginx-certificates
  #   - name: apps-kyverno-policies
  path: ./kubernetes/apps/networking/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: thousand-sunny
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
