---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "staging.tontontresors.com"
  namespace: default
spec:
  secretName: "staging.tontontresors.com"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "staging.tontontresors.com"
