---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tontontresors
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: wordpress
      version: 23.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    replicaCount: 1
    existingSecret: tontontresors
    wordpressScheme: https
    wordpressSkipInstall: false
    wordpressExtraConfigContent: |
      $_SERVER["HTTPS"] = "on";
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: staging.tontontresors.com
      tls: true
    resources:
      requests:
        memory: "300Mi"
        cpu: "50m"
      limits:
        memory: "300Mi"
    mariadb:
      enabled: true
      architecture: standalone
      auth:
        database: tontontresors
        username: tontontresors
        existingSecret: tontontresors
      resources:
        requests:
          memory: "1024Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
