---
originRequest:
  http2Origin: true
  # For letsencrypt staging cert
  noTLSVerify: true

ingress:
  - hostname: "*.${PUBLIC_DOMAIN}"
    service: https://traefik.default.svc.cluster.local
  # - hostname: "*.${PUBLIC_DOMAIN}"
  #   service: http://traefik.default.svc.cluster.local
  - service: http_status:404
