---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app leseditionsdeparis
  namespace: sites
spec:
  interval: 15m
  chart:
    spec:
      chart: phoenix-app
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: mrdotb
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 1
    secret:
      existingSecret: leseditionsdeparis
      create: false
    ingress:
      enabled: false
    image:
      repository: ghcr.io/mrdotb/leseditionsdeparis
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "latest"
    imagePullSecrets:
      - name: leseditionsdeparis-registry
    service:
      type: ClusterIP
      port: 4000
    migration:
      enabled: true
      command: ["/app/bin/migrate"]


---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: leseditionsdeparis-postgresql
  namespace: sites
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    auth:
      username: postgres
      existingSecret: leseditionsdeparis
      database: leseditionsdeparis_db
      secretKeys:
        adminPasswordKey: POSTGRES_PASSWORD
    replication:
      enabled: false
    metrics:
      enabled: false
    primary:
      persistence:
        enabled: true
        existingClaim: leseditionsdeparis-postgresql
    podAnnotations:
      secret.reloader.stakater.com/reload: leseditionsdeparis
