---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sites
resources:
  - pvc.yaml
  - secret.sops.yaml
  - helm-release.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: leseditionsdeparis-registry
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=ghcr.dockerconfig.json.encrypted
