apiVersion: v1
kind: Secret
metadata:
    name: leseditionsdeparis
    namespace: sites
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:XPXnhLAJ5K5YG2XmGG/iIpngBPMrglxgrxND02EicqBTRiEEpToa9SpNCkPdKUCVsS2Ku2LatW8daSqMmqP6bINlnBrKa4Y9OOIFqabUByE2zMwp0+UB0XUcRCfQ,iv:boMmPwqq5HTKIJ92y5Xwx2ECIyi7WgD3Y4MyXJOnzzw=,tag:Mjd1hAZqN3crpCUBYuAJFA==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:uDbrkx7mhQqMBm/nx+4CqfhiQyP1Uy2XVNX9f366gnvuBsBElrAnXaRWHaZRAGJgS4hRoS3HqY4DxCLQxE8x/g==,iv:58lQx89bZRjfkmo2N+qPTzY76/TiUI6AN+o9X2JvFw4=,tag:KvYrqunLjcL4FUzB8w0Wew==,type:str]
    PHX_HOST: ENC[AES256_GCM,data:5gse+juwSURYmqGV4N24eT5lSjPmjrU7myMW7NfV,iv:hAt9YNxF5t9g+Zium1eq/m6Y/85ouW0E2cbJ0y51lg8=,tag:I8bazXYKldauA+egxgmiFQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:y6veRRj8S6pvcjVt36sFKA==,iv:r1Nb29OXmg83t4Vomau9gZ02kRE7b2XcBSUSiXrqOMk=,tag:xtxzHlHW8pVX8fMdbCzMuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY1lJZUFHT3NEV09vVWJU
            bzR4UWxZd1V2MUR0TmJzSHMrcjZBd1cyblhNCm9WVE05MUpuRmRGekVqM3h1NE1W
            eHlhVGMrc0tFeStkb3JEcy9vQjMzYzQKLS0tIEpDaEVzMFMySWt5K3I1cjR1UTdt
            TnU4SmtEcEdGS2RWQlpZUTdGSlNmdTQKeQyPiHQGZbeXUuauF/WtOiGBvUZ7ArKG
            yHGtYy5IyAIWa5ho2yKf3nKIppVhufp/OzjeQjCoB9CutMwDGU/eYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-08T22:26:36Z"
    mac: ENC[AES256_GCM,data:UxkuZQPcCW8TI2Fcl3v6DU+bOEkgTI6IyLkWI6/aK41oCyeAvahNjqblT5sL7Lss1vb5gJp3AM0vuYO+kfgRPyMeazBs6ur4BFtdZemL25TTAYMOnDcQuSt4TIepj5mWbbPTm57jmwoi7nxjYT4Rs9YB2eeDHF9W8Rkrn9bcsNA=,iv:CMUrvDTz8Ce27ja2SxHaA0VBsSBxDxk+QNMV/5JqrGE=,tag:pyD1ei0rnNlp45hoFViqWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
