---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: baptiste.chaleil@protonmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: baptiste.chaleil@protonmail.com
            apiTokenSecretRef:
              name: cloudflare
              key: api-token
        selector:
          dnsZones:
            - "${PUBLIC_DOMAIN}"
            - "*.${PUBLIC_DOMAIN}"
            - "leseditionsdeparis.com"
            - "*.leseditionsdeparis.com"
            - "tontontresors.co"
            - "*.tontontresors.co"
            - "leagueofreplays.co"
            - "*.leagueofreplays.co"
