apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:0kzdi90EbRqUOEWXI0E8/lw2ehDAA2h2f2iacmAZnZjbQLHF35veCQ==,iv:H7E5pQ4C1BcaKdrHpdI7+bJS9l35g1ZATgS7Rnwq5aY=,tag:a2/N4wKzlCrR4L4BTYz/TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYVpjdmZOTTZLcjE5Rnkz
            Wmp5SXRaYnZ4eGxDMldyTlUyZEdjNVNONWowCkRsNzNxMzFhWjNiQkI5VnpHaFdU
            aTgyN0RJcGZ6SXgyaEwwcUFER0tFMVEKLS0tIERGOGc2bVZBSFl6OHpzc1N3QlJV
            NTE5WHFGWDMyRW1TaE1kRE5PZjJ1dHcKss6NJ1+3OzmX99hSNoCZjFblyPm9ienV
            yFzxw1iRi8fg4Lf1NQ9eOxJ1Y9jTHnCsWdgxl7XdBQecZyt8Vb7HwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T21:04:48Z"
    mac: ENC[AES256_GCM,data:W0qobMtkQmKDjObhIGYXkK92Um4z1ma/5kooWKenPBWATN1/BB7d3CRWuliG+RLSuUf3gipZnew+9bwNkMVThSr74KpJ7kWeyL+XjecH3juKB0hwv8PiBPcrxmsK7yipZ/tMjaeXg9podKdsMCnXSrvdf9wq3d9kbGGylnaARSo=,iv:O5dyCahtr1ojpvY9yuklpuZLcO2QmjTZAzujW/8S88I=,tag:qmo8oFijtRRMsQkmwHqHDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
