---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/cloudflared/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: thousand-sunny
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
