---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./leseditionsdeparis/ks.yaml
  - ./lor/ks.yaml
  - ./probuild_ex/ks.yaml
  - ./scarfsage/ks.yaml
  # - ./dotb/ks.yaml
  - ./vintagesta/ks.yaml
