apiVersion: v1
kind: Secret
metadata:
    name: scarfsage
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2B5yr1QlC9ooCjBMWUc=,iv:iByi03Oq/Fh5px6wTQ7VjR+rne0ow0Zmpf0BsGIR9y4=,tag:j0ALBkkqlLHa3lWTqwt+Cw==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:5ZKGiVODuvSZnR6VZp+NrVl9ACuV6I6VEb5YVKUdYiq8tvJMj7L3cKcl/tW0SNzaWksurCW9+aKbbaV+MW9TX+Z+yug0lo8YsivjubDilXkI5YdyDkHMSlW8X4TOW9mm3+IcQzT7rbknswqCIU8MxFAp4qS10OLjIcPD8Pd1feQ5jWndvdIY57E7gKS6Goc/lP1qpw==,iv:ObdGPkrIk/6CUumZqKepYmGUXzBnvTj1f4Yvu2zGz7Y=,tag:tqHJLxvR28L3OlD+KDolxg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:2Z339oJ2vm044TKrAOUKfJyozhGfy/jeN77D6ffxGw8pbYqwxEoeJ5ghqF4lh91RpO8kxXehYegRIFhY81mfzQ==,iv:laln+viEOIYqhZE+YvvsIUhLCh62Y6PXVuMXAgj0I70=,tag:63UJC9w1DYHlNR0TdTdrBg==,type:str]
    PHX_HOST: ENC[AES256_GCM,data:Kji0Cby4B8qsxpOs4g==,iv:d1LwGBSsAtOXkoF+JKFQHgj9S4GPZglY93QQeZe8yIk=,tag:xg++Q2fERzITxR0+kMJTBA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:0k7s/bann5F41z+bD3bOr6i1IpI=,iv:m5iE5FMVfScjnCm4xeNoyxSGzMC7YaqRaBGxG/135k8=,tag:HumINg9yboloDtUXML58fw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ERYsMQYbEflLUBFUuBccGGGSZA5HmXDyUeZ9TkZRYiMQU2dLSNPLbA==,iv:AtPMuhwMrABgrlHY5U7tyEIAiSoJefmwdwoSxseOHOo=,tag:PrTs9iupcexZxdBkKEyQ6w==,type:str]
    S3_BUCKET_NAME: ENC[AES256_GCM,data:uc0lqKUXreDa,iv:iClm0pzsglrYrJ/IHi4rkSwbs8jX1RLur0pci20VHlM=,tag:74+5NcbOEHC+uk8vDaUzZA==,type:str]
    S3_HOST: ENC[AES256_GCM,data:24pS9tYsSvLCVuQK9cM5ycp9jS2u7i2Mmr+ChMWLvg==,iv:wMfhSr1Um/X1pKUyGSXahNhveyQ3YNm0m/kp2NrcVFU=,tag:GnhbtSZbt3exZp6NEfJjDg==,type:str]
    S3_PORT: ENC[AES256_GCM,data:h3V1jQ==,iv:NLHNEgRlofhCuYBrBC+AIn04guWDEczVDHdzzY5iVo0=,tag:1ba4vjFUtYMSLKSfVHmMyw==,type:str]
    S3_SCHEME: ENC[AES256_GCM,data:cDr3J6RgJw==,iv:dt7JUHKft/b/+MiyOx/p0A3L3zwusQ97MFPxnVws310=,tag:njVyS4IZOKjW6R2ZF7S4lw==,type:str]
    ADMIN_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:odw3mhTvlebTFgrd+Qi7MjmVpQ==,iv:JkfQ49WL9fQeOUDvlkBzWlCy2iw9PmDLegr1AbO+tuc=,tag:eS5fzAkeIAtVjl3pkauuSQ==,type:str]
    POSTMARK_API_KEY: ENC[AES256_GCM,data:6o2fSW5wuPlw717zstMQvC4CO/9aNeqiULi0NlkTLkMsKQo5,iv:ur31ky9xbR/wE0e9OzO3++G8yi+lrV40NIZUDLoPal4=,tag:AxYnVLeDVzIZq3OZ7VYciA==,type:str]
    RELEASE_COOKIE: ENC[AES256_GCM,data:7eBgCVM49eifsLUcG6sH0T7UPnw/5+HLq4jGy8IBimqj/Hd5mWpJkEVCYQXzXw9nfh+uqDo1/7Q=,iv:blp73Z4LWdIF7ws8AqbnI0AYHr3xQDylt5WaSntGeFI=,tag:iFZGKUbux5WQq+83mGsnaQ==,type:str]
    STOREFRONT_ACCESS_TOKEN: ENC[AES256_GCM,data:0uyUaY5yHHJEKHFDDwA0mGjRZd5VXPdWpQn6bSUjIiE=,iv:gwMdsRJGjM9qUdfhD+BIc8A7E+4X4/X+g2XymtUuI+8=,tag:7MvxVUHyVzPKBIA7cYRJRg==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:DVhclXecO7kaAbKHOty/DHxLRL2XgUTVn3x60z1NpPjYShvH,iv:FEsJ7ZpatfOTPCC6hkfrs04GrqoGLpdxWjQVYB7Gn8c=,tag:aJgfcNot77Mai8QBMHkHfg==,type:str]
    MEILI_ENDPOINT: ENC[AES256_GCM,data:fIsw9HuDvIPNVwqVeLht22aphn9mtcAyo6jUTROAe2wCrKhaPr/orto9tPVGNNwWP56EHUFuO8Nb8MU=,iv:HO6As1jgIF79BRuTZVvVIRvMmzydxKdppDo6A6kEcco=,tag:vuqUMJuQb2Lj1ZlQBIzOgQ==,type:str]
    EBAY_CLIENT_ID: ENC[AES256_GCM,data:pdcjnHfq7O3k/9EyJzFLUMifjeB9mCAF9TiIzPy2UeUeSzfvkeA2Zw==,iv:lGXT9e+jFsSMqJSiiEp57eoVgYaEeKxPwkspaXCIr/g=,tag:HvhCeuQGAmXQK9piwAly5w==,type:str]
    EBAY_CLIENT_SECRET: ENC[AES256_GCM,data:uO5vVfyv9AS5l5pCKlWaV2kipdVpP6cE2+SgVQFebIWeQMDe,iv:RVlUa7oF/lqdEMp4c7nr64h09BnC0rksH+yJDrxhH8Q=,tag:gXuy5GgDzKtGJ2fZ6nKAkA==,type:str]
    DISCORD_LOGGER: ENC[AES256_GCM,data:zsx/iw==,iv:vUlaCTCdKFLfRtWGSDrYr96JAkCNB6lhdPpIISWw+7o=,tag:zsBL+S+zPtYY0p/4dn4jhg==,type:str]
    DISCORD_GUILD_ID: ENC[AES256_GCM,data:GccIXknVGpICUDJh6o00Myqvug==,iv:0Uht850V2GxrlcmZRElVjKuSka1WyHm++IjOFUPBDtQ=,tag:7dizQ+upulHu5l09BUX+wQ==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:1wFYpyTA4X2mr/tvMmp1xUUNYRJyPInPztjI6Yu5HvPeymZSA9opjRQUOKtEqStMK7pcgo4Os+iVLlgRsA00dYBYeWatWsG9,iv:vdnqjpBxKfI/sDKRdJjcKI5SeT5H4LN6gTHUCDQQMsU=,tag:uMfuaRpbVfWAvnSVs+Ryww==,type:str]
    #ENC[AES256_GCM,data:ohajbkrytWuS1gPhcfc9Ka6Dzw==,iv:DSTseCGsuOBnh1S61fICxgKMwj3dmToXTyiBJX49C34=,tag:GywLiehCqsDP8oWiYPcqAg==,type:comment]
    username: ENC[AES256_GCM,data:pcEJ8trRzBm/,iv:oCwoKW7Oqz1cD5fMV93MpfEjYgQOwZ6ndt2bV9g2juM=,tag:Dd0gFyPuid+OLPuk99qVkw==,type:str]
    password: ENC[AES256_GCM,data:ltQ+e37JRbuW+cwBaqlmvpgPVYO8jVM2pLS6TAgjw8f6StQWnMfxsCOef8MS9O5OViZlZ3EA9Kq9TYFBv47mgg==,iv:9SdnBKru9HmeNow4yUIFh96sZUlKgpVjM23VJClHoJ8=,tag:rCJwUs1uC0mWO1wWWWBWEw==,type:str]
    access_key: ENC[AES256_GCM,data:1BcupAW98nF1ttjKahqXU5Vb2X0=,iv:FcDPNAuosJ4kvItTXcHTf49Ax6Xp3GI/EeOCNOc28Ek=,tag:OivxYj1yHDZb4D7R2V/pKg==,type:str]
    secret_key: ENC[AES256_GCM,data:9yu7WCHMtVOyrusLPlLJg2Ldijk4RQvBSm/L+DC4hQiBFzQQFq6idQ==,iv:oo8Z5LFk66yahATqYrY4W3W5L0BtwzxEs38cT3a2qGY=,tag:l1BJNokyR5fYrwLwtY7iSQ==,type:str]
    #ENC[AES256_GCM,data:62TWioANYsnjVMOTGd1fMG0=,iv:GcvbZKF6uwJl13ERaApPXoDpb411Eb0ewC1aufmA+m0=,tag:kwvYVv862MrtjtXn0F5FEQ==,type:comment]
    backup_access_key: ENC[AES256_GCM,data:S5f97d0YvVlnRI8Ap7i7ovDF71g=,iv:jcR1imhKuYOZeZo5p686HSCuAxeVbsuRtNnZltXoX0c=,tag:ccafN2Xan/7w6qy2rBcFLA==,type:str]
    backup_secret_key: ENC[AES256_GCM,data:96KyPnx5JJWqdqCraacUzjnO2FcuCyApGkAwYtatkyZKuiz21j/dFA==,iv:JdNdbbFG05+oc3bkAbh+QSYxiIXkFLllB9uwIcvNqug=,tag:LICVSUjVINs4oHYBB3mDoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraFJmWTV0cjZLUGtrcG82
            OTR4MWlrb2dEaVB5M0Mya3VWQUhsRTc4SVQ0CmI4VUtid0lrYkUxQ2xwRG9LVW1q
            SkNmV0Z6ZjFWeWJGMmlXUHlZNDFZVlUKLS0tIDYybWRXMlVSVTZYVlNUQVkwWTFY
            V3lWTjlOUVF0dXVOSXdQcmtxWnpSaVEKoGrnDR2DZGS/Smi7mRJTDxptJPkT+++O
            8O3iR7dn8WdOlrRwDMwjriqvaL4FxL6js+NJ3YIeH5L9zytBOAOLMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T14:29:15Z"
    mac: ENC[AES256_GCM,data:2EplUx17qPiDJTlDdZpZzC4fk7j5laNBdSCa62YcXghJKRaHx97o1tbZM+V+TTijNFqgLAdRc8++0UyQuK6/FiqTFfXIeUo7zUg4ih3P76IX4Fchf9Du+bna44/xhaczLZIJfcM9+eFYZSET6s8tCNR6s00XFIF+eUk/5pA+Q5U=,iv:08JBxZuV+EEsbJPvuqrfkoOKG0ZRjhxGGI7QQm8BMDI=,tag:XaMZtELsw6UqSD+wDpVnVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
