---
- name: Update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade
  ansible.builtin.apt:
    upgrade: dist

- name: Install dependencies
  ansible.builtin.apt:
    state: latest
    name:
      - arptables
      - ca-certificates
      - curl
      - dnsutils
      - ebtables
      - ebtables
      - iputils-ping
      - ipvsadm
      - lvm2
      - net-tools
      - open-iscsi
      - python3-kubernetes
      - unzip
