---
- name: Check if cluster is installed
  check_mode: false
  ansible.builtin.stat:
    path: /etc/rancher/k3s/config.yaml
  register: k3s_check_installed

- name: Install Kubernetes
  ansible.builtin.include_role:
    name: xanmanning.k3s
    public: true
  vars:
    k3s_build_cluster: false
    k3s_release_version: v1.28.3+k3s1
    k3s_install_hard_links: true
    k3s_become: true

- name: Kubeconfig
  ansible.builtin.include_tasks: kubeconfig.yaml

- name: Stale Containers
  ansible.builtin.include_tasks: stale_containers.yaml
  vars:
    stale_containers_state: enabled
