---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "leagueofreplays.co"
  namespace: default
spec:
  secretName: "leagueofreplays.co"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "leagueofreplays.co"
