---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app lor
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: phoenix-app
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: mrdotb
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 1
    secret:
      existingSecret: lor
      create: false
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: &host "leagueofreplays.co"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
          secretName: *host
    image:
      repository: ghcr.io/mrdotb/leagueofreplays
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v0.1.0"
    service:
      type: ClusterIP
      port: 4000
    migration:
      enabled: true
      command: ["/app/bin/migrate"]
    resources:
      requests:
        memory: "1000Mi"
        cpu: "20m"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lor-postgres
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0-10
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 10G
  bootstrap:
    initdb:
      database: lor
      owner: lor
      secret:
        name: lor
  # Note: Bootstrap is needed when recovering from an existing cnpg cluster
  # bootstrap:
  #   recovery:
  #     source: &previousCluster postgres16-v1
  postgresql:
    parameters:
      shared_buffers: 128MB
  resources:
    requests:
      memory: "500Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
  monitoring:
    enablePodMonitor: true
  # backup:
  #   retentionPolicy: 30d
  #   barmanObjectStore:
  #     data:
  #       compression: bzip2
  #     wal:
  #       compression: bzip2
  #       maxParallel: 8
  #     destinationPath: s3://ttr-backup/
  #     endpointURL: "https://s3.${PUBLIC_DOMAIN}"
  #     serverName: &currentCluster postgres16-v1
  #     s3Credentials:
  #       accessKeyId:
  #         name: ttr
  #         key: access_key
  #       secretAccessKey:
  #         name: ttr
  #         key: secret_key
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: ScheduledBackup
# metadata:
#   name: lor-postgres-scheduled-backup
#   namespace: default
# spec:
#   immediate: true
#   schedule: "@weekly"
#   cluster:
#     name: lor-postgres
#   target: primary
#   method: barmanObjectStore
