---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app leseditionsdeparis
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: phoenix-app
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: mrdotb
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 1
    secret:
      existingSecret: leseditionsdeparis
      create: false
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: &host "leseditionsdeparis.com"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
          secretName: *host
    image:
      repository: ghcr.io/mrdotb/leseditionsdeparis
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "latest"
    imagePullSecrets:
      - name: leseditionsdeparis-registry
    service:
      type: ClusterIP
      port: 4000
    migration:
      enabled: false
      command: ["/app/bin/migrate"]
    volumeMounts:
      - name: edp-images
        mountPath: /srv/leseditionsdeparis
    volumes:
      - name: edp-images
        persistentVolumeClaim:
          claimName: leseditionsdeparis
    resources:
      requests:
        memory: "302Mi"
        cpu: "15m"
      limits:
        memory: "302Mi"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: leseditionsdeparis-postgres
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0-10
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 10G
  bootstrap:
    initdb:
      database: edp
      owner: edp
      secret:
        name: leseditionsdeparis
  # Note: Bootstrap is needed when recovering from an existing cnpg cluster
  # bootstrap:
  #   recovery:
  #     source: &previousCluster postgres16-v1
  postgresql:
    parameters:
      shared_buffers: 128MB
  resources:
    requests:
      memory: "500Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://leseditionsdeparis/
      endpointURL: "https://s3.${PUBLIC_DOMAIN}"
      serverName: &currentCluster postgres16-v1
      s3Credentials:
        accessKeyId:
          name: leseditionsdeparis
          key: access_key
        secretAccessKey:
          name: leseditionsdeparis
          key: secret_key
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: leseditionsdeparis-postgres-scheduled-backup
  namespace: default
spec:
  immediate: true
  schedule: "@weekly"
  cluster:
    name: leseditionsdeparis-postgres
  target: primary
  method: barmanObjectStore
