---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: leseditionsdeparis
  namespace: default
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: leseditionsdeparis-postgresql
  namespace: default
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10G
