---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "probuild.${PUBLIC_DOMAIN}"
  namespace: default
spec:
  secretName: "probuild.${PUBLIC_DOMAIN}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "probuild.${PUBLIC_DOMAIN}"
