---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app probuild-ex
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: phoenix-app
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: mrdotb
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 1
    secret:
      existingSecret: probuild-ex
      create: false
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: &host "probuild.${PUBLIC_DOMAIN}"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
          secretName: *host
    image:
      repository: ghcr.io/mrdotb/probuild_ex
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "latest"
    service:
      type: ClusterIP
      port: 4000
    migration:
      enabled: false
      command: ["/app/bin/migrate"]
    resources:
      requests:
        memory: "512Mi"
        cpu: "20m"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: probuild-ex-postgres
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0-10
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 10G
  bootstrap:
    initdb:
      database: probuild_ex
      owner: probuild_ex
      secret:
        name: probuild-ex
  # Note: Bootstrap is needed when recovering from an existing cnpg cluster
  # bootstrap:
  #   recovery:
  #     source: &previousCluster postgres16-v1
  postgresql:
    parameters:
      shared_buffers: 128MB
  resources:
    requests:
      memory: "500Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 2d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://probuild-ex/
      endpointURL: "https://s3.${PUBLIC_DOMAIN}"
      serverName: &currentCluster postgres16-v1
      s3Credentials:
        accessKeyId:
          name: probuild-ex
          key: access_key
        secretAccessKey:
          name: probuild-ex
          key: secret_key
