apiVersion: v1
kind: Secret
metadata:
    name: probuild-ex
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:y4boSzqmMO5InE8M0CKq7A==,iv:ZX2g8NJyRqA7RbKnIZbUDghiXwKZhHaUNftm/AYXYv0=,tag:Wg4VfMBajsbfle08uMUfgQ==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:Kd8cBbLsaAd9a4+kFk1QZt/qpY84q3UtQHGKt7cqcKXfLaNAHnxqdo0U2BZzmfoeExPZHEaQmWt5Rw+Zu+pX7V+palrDcuEwzcPCW1x2iwC54YPxE86Xg/dCgzosak5yt5VgMIJKU3fni3OPRLL6kfz9MG8Yr1xnwsqYMC/WH75y2PX7/WM24KE974cPJoYmBdA7Nrx0Jynhkw==,iv:RfICB7IqJPbYCzrMQsGo74Qd6euY1ShYbyT4laKwpSk=,tag:NYEVmO8v2vZGfFcI4iKbMg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:71dOoob6oUl7cTmkfpZyzJUC28uk4WEQ89QQNkBV8nKM/Iq4Hl/jeD3CM2FC85G6qVWXN9oPFiTrXTKn4sndfw==,iv:rfHIg1v/zNZhWo2fyizP94A2FxNPOiOKclZq9KvK4lw=,tag:uXbQFzFM7RCHXMzvbjMQnA==,type:str]
    PHX_HOST: ENC[AES256_GCM,data:/mYXa1cFqjQBIMjuXJUf8crDgQ==,iv:Q3qYcr0d12t4oaoOJW9iTLwc7Mwndjnd4joYYAe6neg=,tag:ggzBwDynHtem9pqL2ulYPg==,type:str]
    RIOT_TOKEN: ENC[AES256_GCM,data:R7IyXGKOhagoXhC1fCZAZKoN9D1GewPr8oTGRbRnixR3ou7IgZzGJ4f7,iv:cPZfpp/kDwqbxXftETEqmyWXoFdIyH8yJgiERg9CecU=,tag:EZUHkSzcxR40QAexNyf9PA==,type:str]
    #ENC[AES256_GCM,data:hBwtOuJfQbDU2LaqyQ==,iv:/rm2ysZ915aZqum/ErpR8ibHP8NrIKtU5PmGti/hcGA=,tag:CIZ5525C2z7C4w9AiI5O9A==,type:comment]
    username: ENC[AES256_GCM,data:U92VkhdJNaqz4f0=,iv:1MK6UPS40jw0S+B0d0cb2mNDAwEKMm8n9Mx2tn3JL9k=,tag:dEG+bsA1pFJheL39h6zpbQ==,type:str]
    password: ENC[AES256_GCM,data:TJm3zwL3jY47iRd27ZaI2PTKb98xYinuvRa4IaRYEuE5+gU5O2z++EARR8fLp6hWOpstNPwBADQc0/COQ67D5Q==,iv:2QhWQ+k6KXs73hOyZikBhZrLYqt7bhzuugcenFkJ9AE=,tag:A9ll+AGIio8AgoxIVvUEXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MTdHNGJCcWlHaFFQQklQ
            NjZPSEl1Q0F6RVcvNmZWK2NlZFIxTVpFeUNrCmZnanVWTmhhYy93eWRQdGdTaVJi
            M0ExbkR0R3hrck96cGtQT2k3dTk2Z3MKLS0tIFc3TXkyUytoZjlHZXdnb0tBUXJB
            Q2NNNWdHTXRxMzJaSlh4TmpkQkZtRDgKp5GEtGKIWCepoNQQOWB2Dfkg3ZrfTQBE
            XMLjxskoaW4JVPxhAUui2o1KPOBX+HrmrhFLm6OI8J/j+60pXtOY4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-01T13:34:16Z"
    mac: ENC[AES256_GCM,data:pFb8uijtKQA70PM8jSB3twq952bvCFl1DYBfEvnnntBex5wbv3z22eYQF3K1qhTFKB6S7YQu26G6ArAwvUDMfr9N5NxQimxQHNL5wVk7v9cCIP6hod9D9IsqnNGY9y6lNiLFfEbKSm+Dr8gTfa3N9gBxlscUYEgfkJogOcctHUo=,iv:NR0Hq23GVwNKX3AThIVkj+0KHvgYYtZ2F20EakrvCvI=,tag:sgjJaPhzO2ievBeqvrH1YA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
