apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:mDoQQPc6,iv:JLvE5rMtZGgiKYx95/7JCU1EDmkky78zdKeYjBcWg+8=,tag:kSVXVLq+XoBxXaXbcoPDVA==,type:str]
    # password need to be bcrypt
    password: ENC[AES256_GCM,data:5gtjuhmdE5sPZYXoKW+SSIpSLqFxjcrtEDpWWy/Y9skEhdJOknm+mgSzdPz8dAKfzlxomAgLEf+wT+3z,iv:szrYnwVdRyZAcC4C2zCvXhbtn99HR5PiM/crBb7Z7IE=,tag:Mm5lq6j0fzQfu+XtNrNBFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcEt0SWtsbFlYdFZDNTZ4
            ZkMyRU82RVdxVFJyNDRHeDNTTERLbE5uRXhZCk1Ta3Nuc1pnNnVyQXlmNnpGaGw5
            b3FhWlhuZk9DMjFZbmx0ZlJiVVpNcjAKLS0tIHk0TGdtc0o0VmR3NWVDNmlFa2kr
            VzAvRkRUZ1dEeS91NWFMTVcyM3E0b00Kgss3tPuMfOznV3JVoOcHyuo0iEFEPjrs
            4i05Atwoe/UldTN60x8zaNODF0vHK2JcRyXbbjZBEllXSXorbnbu6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T20:53:27Z"
    mac: ENC[AES256_GCM,data:btgoPO5HOUqA3fRJjsJRETjtCctIBOB4HSd4fXF2uDTyw6PbL2mGsnX/+pU74lfjysZUZjHyjM4W0X76xxkSM8CUaGc39QXaK/SaKicRxpmuupQGAAmqS3jWn8TOPf74ollAMqkkxNv1xEqLWQQdgOCOpAVf4NtP4+Q8NtASDrw=,iv:4WTIzk4NLIsHOG0Dqe8LCug8ATAwyRwvLqFBorC/fRU=,tag:ig3pOcxjADoPGUeH29aggA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
