---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "vintagesta.com"
  namespace: default
spec:
  secretName: "vintagesta.com"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "vintagesta.com"
