---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vintagesta
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: wordpress
      version: 23.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    replicaCount: 1
    existingSecret: vintagesta
    wordpressScheme: https
    wordpressSkipInstall: true
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: vintagesta.com
      tls: true
    mariadb:
      enabled: true
      architecture: standalone
      auth:
        database: vintagesta
        username: vintagesta
        existingSecret: vintagesta
