# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 52.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      enabled: true

    ### Component values

    alertmanager:
      enabled: false

    kubeApiServer:
      enabled: true

    kubeEtcd:
      enabled: false

    grafana:
      enabled: true
      adminPassword: onizuka

      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          # Allow discovery in all namespaces for dashboards
          searchNamespace: ALL

    prometheus:
      prometheusSpec:
        # Ensure all PodMonitor / ServiceMonitor resources are picked up properly:
        # https://stackoverflow.com/questions/68085831/add-podmonitor-or-servicemonitor-outside-of-kube-prometheus-stack-helm-values
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
