---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: thousand-sunny
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/mrdotb/thousand-sunny.git
  ignore: |
    # exclude all
    /*
    # include cluster directory
    !/kubernetes

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: thousand-sunny
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        # - kind: Secret
        # name: cluster-secrets
