---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata
  namespace: analytics
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 10G
