apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:/aebcu3xDUWwZw==,iv:bwx/cx3V0P91UrhTc6dymMLnMBv9b5BTtywOcuut0Wo=,tag:JC6VD2n3XpXompc6V7ZWMg==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:RNPKcECnZIvTrCykBGK2+XVaKGCIhfIzxPLN61QPzGDlob1dsCiJbQ==,iv:LD/q6ZS5DcJz7OdZyd96iWlZHFGBqeMI1w+KG9DbDag=,tag:NsRMnAdWpgiVaQQPmE4kWg==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:I49kdyJsfDBRzFzfyC27ue8Qw2ZekI67qOlFvShbT5f/gpbQ,iv:V3kaYdUlut5flM+/zObBXgLsGL3rCbXlkHEQaKr2biA=,tag:EEryKJhAGPPAo0pnNUgL5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdmNVM2JxZ0RLVmJ2ZE1n
            Rjc3Lzd5RzBBMmZnT3VmRldVSmJLVHRTRGxJCkdZQlhua214aEE2NWZNbUtpUTFJ
            SWVpd2lCNFRCZlR3WTNKZXpmUjkrM0EKLS0tIFJqTlViSVo3cmE3THN6YUc3MHlh
            U2REak9CTkxpcDh3aVFQRmplMnF0S28KogZ7RzObaeHDedqn/f0DZs44s1fflj1j
            Zs8ozitEvi/Gsl5EqTPPZKmJA97ZhXjCiT3hRPjdbwPpIS9gm1yrMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-20T21:36:34Z"
    mac: ENC[AES256_GCM,data:4ZC82DhFpelCpIe43/ljrwoFSoANSIziyvlwFLtwGsY2ZW/nuPemBMXFXZ2tOwWtj3A6oXOmFvZddwyiQOrMOgRsDwVoUwOaFOuR2Ga2Ds1f6aarWo205MFsQGlbl9JzbIEVKBBcFdLbfxYi5w4qWS9mjCG69BZoID3K3RhZtUM=,iv:MhgyUOVPyzfMccvbLd45OYogUhJO2FJ/P7tNExWEQ8s=,tag:6REGbtCyeGNHx43g9Tglnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
