apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:i+lz7udMvI+anEg=,iv:qd1qVMiNLpm/V6TG+ZoKrZdAXlXH146Q3C6nRnNS3U0=,tag:hZoMLI57EIyirWA/cTu1pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdmNVM2JxZ0RLVmJ2ZE1n
            Rjc3Lzd5RzBBMmZnT3VmRldVSmJLVHRTRGxJCkdZQlhua214aEE2NWZNbUtpUTFJ
            SWVpd2lCNFRCZlR3WTNKZXpmUjkrM0EKLS0tIFJqTlViSVo3cmE3THN6YUc3MHlh
            U2REak9CTkxpcDh3aVFQRmplMnF0S28KogZ7RzObaeHDedqn/f0DZs44s1fflj1j
            Zs8ozitEvi/Gsl5EqTPPZKmJA97ZhXjCiT3hRPjdbwPpIS9gm1yrMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T19:56:01Z"
    mac: ENC[AES256_GCM,data:bUjSTXssCk0k5OykghZ4sF8ZgBmrEqndM7Lbb5ozXXX5AgCMbB3KUfev/4Jp6i2pXPq+qoW3c1Jt+eOTyqgAjqAMwTXx4YMW8Kf91B48PdKiqupdT7hTabrTgfzQ/56E2AubFs8g9jrCH317A+7aupH5S0PuyHlbm0a62umnkGI=,iv:dP4/qaOwM/d4UrCwhoLYWVg9ZOjD7yvUxL64A1jEDPE=,tag:hD3qeUG9QE2CzpBwxT4UYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
