apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:/aebcu3xDUWwZw==,iv:bwx/cx3V0P91UrhTc6dymMLnMBv9b5BTtywOcuut0Wo=,tag:JC6VD2n3XpXompc6V7ZWMg==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:PQ5cEUhictOsIyTTf80YOlu7IODORdYpWAWjCCtUrs3q3Kf0i9nSsw==,iv:yLA/aStvasvEHeUKrR0FvOkGmiaEKG5siMresw6mp0U=,tag:oVHifQelNLvi4fzlZPxxGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdmNVM2JxZ0RLVmJ2ZE1n
            Rjc3Lzd5RzBBMmZnT3VmRldVSmJLVHRTRGxJCkdZQlhua214aEE2NWZNbUtpUTFJ
            SWVpd2lCNFRCZlR3WTNKZXpmUjkrM0EKLS0tIFJqTlViSVo3cmE3THN6YUc3MHlh
            U2REak9CTkxpcDh3aVFQRmplMnF0S28KogZ7RzObaeHDedqn/f0DZs44s1fflj1j
            Zs8ozitEvi/Gsl5EqTPPZKmJA97ZhXjCiT3hRPjdbwPpIS9gm1yrMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T15:52:50Z"
    mac: ENC[AES256_GCM,data:T5TYj5zeCxyWfUIG5EzI6qQJdViu8aP+CCSPTusc4uwnwScDd9FD0LohGVERt8O5y4QQSKOpaRZAFIcUfGl9RfVqv7Nr/yCuzmTd4mVJFcurvTYLU9KlnmhHzkejZiX4QS9rTcJ0fBC0kNfA8IfKGQAe9apbWiIVhslveEigeFo=,iv:Hg2T2hwtQRyZLZ6l3iFptVlkeiqOaaQWgJtPKybiEeI=,tag:cKym478MXY/58ZGKijlE6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
