---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-cert-manager
  namespace: flux-system
spec:
  path: ./kubernetes/apps/cert-manager/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: thousand-sunny
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
