---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "plausible.${PUBLIC_DOMAIN}"
  namespace: analytics
spec:
  secretName: "plausible.${PUBLIC_DOMAIN}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "plausible.${PUBLIC_DOMAIN}"
