---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plausible
  namespace: analytics
spec:
  interval: 15m
  chart:
    spec:
      chart: plausible-analytics
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: mrdotb
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    baseUrl: "https://analytics.${PUBLIC_DOMAIN}"
    listenIp: 0.0.0.0
    google:
      enabled: true
    postgresql:
      enabled: false
    clickhouse:
      enabled: false
    secret:
      existingSecret: plausible
      create: false
    ingress:
      enabled: true
      className: traefik
      path: /
      pathType: Prefix
      hosts:
        - &host "analytics.${PUBLIC_DOMAIN}"
      tls:
        - hosts:
            - *host
          secretName: *host
      annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: file-multiple
    podAnnotations:
      secret.reloader.stakater.com/reload: *app

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: plausible-postgres
  namespace: analytics
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0-10
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 10G
  bootstrap:
    initdb:
      database: plausible
      owner: plausible
      secret:
        name: plausible
  # Note: Bootstrap is needed when recovering from an existing cnpg cluster
  # bootstrap:
  #   recovery:
  #     source: &previousCluster postgres16-v1
  postgresql:
    parameters:
      shared_buffers: 128MB
  resources:
    requests:
      memory: "500Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
  monitoring:
    enablePodMonitor: true
  # backup:
  #   retentionPolicy: 30d
  #   barmanObjectStore:
  #     wal:
  #       compression: bzip2
  #       maxParallel: 8
  #     destinationPath: s3://cnpg-zd6qkutg/
  #     endpointURL: https://${SECRET_CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
  #     serverName: &currentCluster postgres16-v1
  #     s3Credentials:
  #       accessKeyId:
  #         name: cloudnative-pg-secret
  #         key: aws-access-key-id
  #       secretAccessKey:
  #         name: cloudnative-pg-secret
  #         key: aws-secret-access-key

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plausible-clickhouse
  namespace: analytics
spec:
  interval: 15m
  chart:
    spec:
      chart: clickhouse
      version: 4.0.10
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    auth:
      username: clickhouse
      existingSecret: plausible
      existingSecretKey: CLICKHOUSE_PASSWORD
      database: plausible_events_db
    initdbScripts:
      db-init.sql: |
        CREATE DATABASE IF NOT EXISTS plausible_events_db
    # https://github.com/plausible/analytics/discussions/1603 clickhouse cluster is not supported
    shards: 1
    replicaCount: 1
    zookeeper:
      enabled: false
    metrics:
      enabled: false
    persistence:
      enabled: true
      existingClaim: plausible-clickhouse
    podAnnotations:
      secret.reloader.stakater.com/reload: plausible
