---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plausible
  namespace: analytics
spec:
  interval: 15m
  chart:
    spec:
      chart: plausible-analytics
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: mrdotb
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    baseUrl: "https://plausible.${PUBLIC_DOMAIN}"
    listenIp: 0.0.0.0
    google:
      enabled: true
    postgresql:
      enabled: false
    clickhouse:
      enabled: false
    secret:
      existingSecret: plausible
      create: false
    ingress:
      enabled: true
      className: traefik
      path: /
      pathType: Prefix
      hosts:
        - &host "plausible.${PUBLIC_DOMAIN}"
      tls: []
      annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: file-multiple
    podAnnotations:
      secret.reloader.stakater.com/reload: *app

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plausible-postgresql
  namespace: analytics
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    auth:
      username: postgres
      existingSecret: plausible
      database: plausible_db
      secretKeys:
        adminPasswordKey: POSTGRES_PASSWORD
    replication:
      enabled: false
    metrics:
      enabled: false
    primary:
      persistence:
        enabled: true
        existingClaim: plausible-postgresql
    podAnnotations:
      secret.reloader.stakater.com/reload: plausible

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plausible-clickhouse
  namespace: analytics
spec:
  interval: 15m
  chart:
    spec:
      chart: clickhouse
      version: 4.0.10
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    auth:
      username: clickhouse
      existingSecret: plausible
      existingSecretKey: CLICKHOUSE_PASSWORD
      database: plausible_events_db
    initdbScripts:
      db-init.sql: |
        CREATE DATABASE IF NOT EXISTS plausible_events_db
    # https://github.com/plausible/analytics/discussions/1603 clickhouse cluster is not supported
    shards: 1
    replicaCount: 1
    zookeeper:
      enabled: false
    metrics:
      enabled: false
    persistence:
      enabled: true
      existingClaim: plausible-clickhouse
    podAnnotations:
      secret.reloader.stakater.com/reload: plausible
