---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-postgresql
  namespace: analytics
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: plausible-postgresql
  storageClassName: local-path
  resources:
    requests:
      storage: 10G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-clickhouse
  namespace: analytics
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: plausible-clickhouse
  storageClassName: local-path
  resources:
    requests:
      storage: 10G
