apiVersion: v1
kind: Secret
metadata:
    name: plausible
    namespace: analytics
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZWOfyyFf7cyAHZyCTkmX6A==,iv:/pfbUPlkAeTkeSuVZAw3kxMvOfVp4UAs2G823P5/nnw=,tag:k0MMrVdcEeHYDgdqCogu8A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Ky9Qz8WWi4fMeK5Ww7JtUUbzjzWLupRWy+Ck2frGuBcnoRTxNBiZACStziXZJVTMJifKAuxuwASCvj0q/XbDu5EMWSpUSS3hHA==,iv:dFxdVgzn8kCkav3H9XcqVOKfMuD67s/tJ6nW8eH+RMg=,tag:j0wEL+4SQtmAwJtLMgGEBg==,type:str]
    CLICKHOUSE_DATABASE_URL: ENC[AES256_GCM,data:JtPIaSrbwQr07ZkpDYjf9e8pOWdg0SebgvPhvbT2krtqHeBY+DfuZ2mR+ZW0MSLcF61x7LrIatLt+i4Hmg6JkGapRIIJpWEhHLv8reMSXUo=,iv:NKl2zvYH6gR9k3CnnjxCIvkOczvFDbKpHtISW/Tpvj8=,tag:iwXNjOuV8TlF3xpbsNVPpw==,type:str]
    CLICKHOUSE_USER: ENC[AES256_GCM,data:xUTpPRNOls2/8w==,iv:1sZYTyzl1L6SXjf9VuhvjdsHWNYPnEIsLT6NoPz0o30=,tag:Un5qvP+RaCjpu+LXJiE/0w==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:FAic4zvdcu0kKEYeco9SuQ==,iv:Jfh86lnrtnFJrNmIsItTTRZDXJW58l2r1uQvx2b02F4=,tag:Yjo6f1lxyE2cudiLhzGUsw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:GCpd2fuSfeuPZPphFI9fJ2M99SroOXcKi8z1O6lw0qESH7g1MZZ2UUzt+xxO6pA1t2AT6snRPj4accLCCM56uOrXFCEXCgLp,iv:g2QdB7Awqa2w9VKvnT13b3XamrwZDiJrsjT9+DOBDW0=,tag:dnvmX/MKLiiALIPTi/Qd/g==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:NFSj96z3z1Uly4bvOIkl0d9sBPhIrmaDblPPyzdE0WopxQw=,iv:rOKJU9xoiGHTTsngj8pEFY0Cj6p2eDBUB13ekBlS6pc=,tag:vDUijNJP8q48AfJLxce5Aw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:hOfA8wWd95E8d6crZTmo0GN8XnX9+dgZ5RuXAw9yP6zOWeWhKRBy1bCmZHgPayVI7jjpEYbj6yo8axxQ7oOKfQ==,iv:CHMTsbQzwu6DWKG7jmdGxf4mBFzvbXkJw+QiVsFkG/8=,tag:QA+8m2gMt2cTAl/TNOuxlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15s5tpgh6pwznwjah5w50vkdzhamc7lgmfv2s8mnyh6s3rg7g7fmsjav0fw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkR1o4bkd3YTUwUnZMR0hu
            cjNOREN5Z3c2NURxcVRCV09wdUpNRzIrblNjCnhYdUVWNTFGSE5lcWtQWXF1bXRl
            MWc1K0UyazhVQjQvaWVOd3pPeVR3b3MKLS0tIFRaWnRXQU1sblp6dGhseU1jeGxO
            QTMrUHJXNVRYbmQ3SHY3djFMNkF5aEkKQvvV+QWVhEu6/zNrCw/qFQWfS/sM8lcJ
            59vuoh/5RtbTRfBLApcUV/4CCCFLNYrc5QHfx69A7YrVho7pPmOqhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-31T11:06:24Z"
    mac: ENC[AES256_GCM,data:IRk7R/51OneOfBKC6HpSIDAynE8jTu7Obi+NSW+jtBIZIn13WpkhzEVueJDNoNtAcmoofuycPBqbAwiR8r+jMJG8KQhaWFesYCpKRP+n5rAxiSCc10MYMsHtc7H9+YZLdtCb3ZKqVfH3b3X2089gYXv185e5xH7xiIv7Pm47ODM=,iv:yAtWuE3gj5ayvTrxx5NnmOV2F0amXxo6IVIxZJ8bRqs=,tag:uUzcOUvKmnEz0puQGtRIbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
