# On the initial install, Flux will get 'clogged' unless you incrementally add pods.
# Start with flux-system, kube-system and networking.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - analytics
  - cert-manager
  - database
  - default
  - flux-system
  - kube-system
  - monitoring
  - networking
  - storage
