---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "dotb.io"
  namespace: default
spec:
  secretName: "dotb.io"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "dotb.io"
