---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app dotb
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: phoenix-app
      version: 0.2.5
      sourceRef:
        kind: HelmRepository
        name: mrdotb
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    app: dotb
    replicaCount: 1
    secret:
      existingSecret: dotb
      create: false
    labels:
      app: dotb
    extraEnv:
      - name: PHX_SERVER
        value: "true"
      - name: K8_NODE_BASENAME
        value: "dotb"
      - name: LIBCLUSTER
        value: "true"
      - name: EXTENSION_VERSION
        value: "3.17.0"
      - name: AI_FEATURES_ENABLED
        value: "true"
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: &host "dotb.io"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
          secretName: *host
    image:
      repository: ghcr.io/mrdotb/dotb
      pullPolicy: Always
      tag: "v0.175.0"
    imagePullSecrets:
      - name: dotb-registry
    service:
      type: ClusterIP
      port: 4000
      healthcheck: /up
    migration:
      enabled: true
      command: ["/app/bin/migrate"]
    resources:
      requests:
        memory: "4Gi"
        cpu: "3"
      limits:
        memory: "4Gi"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dotb-postgres
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4-45
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 10G
  # bootstrap:
  #   initdb:
  #     database: dotb
  #     owner: dotb
  #     secret:
  #       name: dotb
  # Note: Bootstrap is needed when recovering from an existing cnpg cluster
  # bootstrap:
  #   recovery:
  #     source: &previousCluster postgres16-v1
  # bootstrap:
  #   recovery:
  #     source: &previousCluster backup
  # externalClusters:
  #   - name: backup
  #     barmanObjectStore:
  #       data:
  #         compression: bzip2
  #       wal:
  #         compression: bzip2
  #         maxParallel: 8
  #       destinationPath: s3://dotb-backup/
  #       endpointURL: "https://s3.mrdotb.com"
  #       serverName: postgres16-v1
  #       s3Credentials:
  #         accessKeyId:
  #           name: dotb
  #           key: backup_access_key
  #         secretAccessKey:
  #           name: dotb
  #           key: backup_secret_key
  postgresql:
    parameters:
      shared_buffers: "1GB"
      work_mem: "16MB"
      maintenance_work_mem: "512MB"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
  resources:
    requests:
      memory: "8Gi"
      cpu: "2000m"
    limits:
      memory: "8Gi"
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://dotb-backup/
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      serverName: &currentCluster postgres16-v1
      s3Credentials:
        accessKeyId:
          name: dotb
          key: access_key
        secretAccessKey:
          name: dotb
          key: secret_key
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: dotb-postgres-scheduled-backup
  namespace: default
spec:
  immediate: true
  schedule: "0 0 3 * * *"  # Every Day at 03:00 UTC
  cluster:
    name: dotb-postgres
  target: primary
  method: barmanObjectStore
