---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "status.${PUBLIC_DOMAIN}"
  namespace: monitoring
spec:
  secretName: "status.${PUBLIC_DOMAIN}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "status.${PUBLIC_DOMAIN}"
