---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatus
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: gatus
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: minicloudlabs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  values:
    persistence:
      enabled: true
    config:
      storage:
        type: sqlite
        path: /data/data.db
      endpoints:
        - name: Leagueofreplays
          url: https://leagueofreplays.co
          conditions:
            - '[STATUS] == 200'
        - name: Leseditionsdeparis
          url: https://leseditionsdeparis.com
          conditions:
            - '[STATUS] == 200'
        - name: ScarfSage
          url: https://scarfsage.com/hermes-scarves
          conditions:
            - '[STATUS] == 200'
        - name: Dotb
          url: https://dotb.io/up
          conditions:
            - '[STATUS] == 200'
    ingress:
      enabled: true
      ingressClassName: "traefik"
      hosts: [&host "status.${PUBLIC_DOMAIN}"]
      tls:
        - hosts:
            - *host
          secretName: *host
